name: deployment
on: [push]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: deploy gateway application
        uses: appleboy/ssh-action@v1.0.0
        env:
          INPUT_PATH: ${{ secrets.APP_WIKI_TEMPLATE_PATH }}
          INPUT_WIKI_PATH: ${{ secrets.APP_WIKI_PATH }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          allenvs: true
          script: |
            cd $INPUT_PATH
            git pull
            cd $INPUT_WIKI_PATH
            hugo mod get -u
